### ISSUE TITLE
Ponte RabbitMq Config

### ISSUE THREAD

**Issue by raguram-github** [mcollina/ponte#6]
Hi I am trying to use RabbitMq as broker for Ponte. But I am getting following error

Command : sudo DEBUG=ascoltatori:amqp ponte -c pontemongoconfig.js  | bunyan

Error:  
  ascoltatori:amqp connecting to undefined +0ms
  ascoltatori:amqp connected +8ms
  ascoltatori:amqp created exchange ascolatore5672 +2ms
  ascoltatori:amqp subscribed to queue +5ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickCallback (node.js:442:13)

---------------------------------------------
My congif fle

module.exports = {
  persistence: {
    // same as http://mcollina.github.io/mosca/docs/lib/persistence/mongo.js.html 
    type: "mongo",
    url: "mongodb://localhost:27017/ponte"
  },
  
 broker : {
  type: 'amqp',
  json: false,
  amqp: require('amqp'),
  exchange: 'ascolatore5672'
},
  logger: {
    level: 10, // or 20 or 40 
    name: "MongoPonte"
  }
};

-----------
node -v
v0.10.36
npm -v
1.4.28
Mac 10.9.5. 

-------------
I took the broker config from ascoltatori config content.

Can you guide me on how to configure RabbitMq as broker for Ponte?

**Comment by mcollina** [comment]
You probably have some other thing running on the same ports Ponte is using.
Ponte by default listen to 1883 (the standard MQTT one). If you use RabbitMQ, you would need to disable MQTT support in Rabbit or change the port in Ponte.
